- name: Update and upgrade apt packages
  apt:
     upgrade: full
     update_cache: yes
     cache_valid_time: 86400 #One day

- name: Install packages
  apt:
    name:
    - net-tools
    - curl
    - git
    state: latest
    cache_valid_time: 3600    # update cache if more than an hour old
 

- name: Update and upgrade apt packages
  apt:
     upgrade: full
     update_cache: yes
     cache_valid_time: 86400 #One day    


