---
# This is a sitewide playbook   cmd> ansible-playbook site.yml -i hosts 
# filename: site.yml
# ansible -i hosts vmware -m ping
# An Ansible Playbook is formatted with YAML, Yet Another Markup Language. 
# This means that the whitespace is significant and items at the same configuration level 
# should be spaced the same as other sibling elements. 
# Installing is by using the following , we should execute the command from this directory 
# and the inventory, ansible.cfg and playbook should also be in this directory.

#20200707
# - include: apt_get_update.yml
# - include: clone_socialcoin_api.yml
# - include: install_mysql.yml
 - include: install_nodejs_10_18_1.yml
 - include: install_nvm_8_11_3.yml
 - include: config_socialcoin_api.yml
 - include: install_nginx_www_server.yml 
 
